import { IPublicFigure } from '../models/public-figure.model';
export const CHARACTERS: IPublicFigure[] = [
    {
        id: 1,
        name: 'Kanye West', 
        publicationDate: new Date(),
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi ducimus voluptates magni.",
        qtyLikes: 32,
        qtyDislikes: 18,
        image: '/assets/images/west-cut.jpg',
        category: 'Entertainment',
        wikiUrl: 'string',
        votingText: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae nisi quaerat quasi quam modi numquam eius odit praesentium ad? Ab asperiores exercitationem natus dolore! Vitae?',
        heroImage: '',
        endVotingDate: new Date (),
    },
    {
        id: 2,
        name: "Mark Zuckenberg", 
        publicationDate: new Date (),
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi ducimus voluptates magni.",
        qtyLikes: 18,
        qtyDislikes: 32,
        image: '/assets/images/mark.jpg',
        category: 'Business',
        wikiUrl: 'string',
        votingText: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae nisi quaerat quasi quam modi numquam eius odit praesentium ad? Ab asperiores exercitationem natus dolore! Vitae?',
        heroImage: '',
        endVotingDate: new Date (),
        
    },
    {
        id: 3,
        name: "Cristina Fernandéz de Kirchner", 
        publicationDate: new Date (),
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi ducimus voluptates magni.",
        qtyLikes: 200,
        qtyDislikes: 400,
        image: '/assets/images/kirchner.jpg',
        category: 'Politics',
        wikiUrl: 'string',
        votingText: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae nisi quaerat quasi quam modi numquam eius odit praesentium ad? Ab asperiores exercitationem natus dolore! Vitae?',
        heroImage: '',
        endVotingDate: new Date ()
    },
    {
        id: 4,
        name: "Malala Yousafzai", 
        publicationDate: new Date (),
        description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi ducimus voluptates magni.",
        qtyLikes: 200,
        qtyDislikes: 130,
        image: '/assets/images/malala.jpg',
        category: 'Activism',
        wikiUrl: 'string',
        votingText: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Repudiandae nisi quaerat quasi quam modi numquam eius odit praesentium ad? Ab asperiores exercitationem natus dolore! Vitae?',
        heroImage: '',
        endVotingDate: new Date ()
    }
];